version: '3.4'

name: microservices-environment
services:
  rabbitmq: # login guest:guest
    container_name: rabbitmq
    image: rabbitmq:3-management
    hostname: "rabbitmq"
    labels:
      NAME: "rabbitmq"
    ports:
    - "4369:4369"
    - "5671:5671"
    - "5672:5672"
    - "25672:25672"
    - "15671:15671"
    - "15672:15672"