kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: keycloak
  namespace: microservices
  labels:
    app: keycloak
    app.kubernetes.io/component: keycloak
    app.kubernetes.io/instance: keycloak
    app.kubernetes.io/name: keycloak
    app.kubernetes.io/part-of: microservices
spec:
  tags:
    - name: latest
      from:
        kind: DockerImage
        name: 'quay.io/keycloak/keycloak:latest'
      importPolicy:
        importMode: Legacy
