kind: Service
apiVersion: v1
metadata:
  name: keycloak
  namespace: microservices
  labels:
    app: keycloak
    app.kubernetes.io/component: keycloak
    app.kubernetes.io/instance: keycloak
    app.kubernetes.io/name: keycloak
    app.kubernetes.io/part-of: microservices
    app.openshift.io/runtime-version: latest
spec:
  selector:
    app: keycloak
    deployment: keycloak
  ports:
    - name: 8443-tcp
      protocol: TCP
      port: 8443
      targetPort: 8443
    - name: 8180-tcp
      protocol: TCP
      port: 8180
      targetPort: 8180
  
