kind: Deployment
apiVersion: apps/v1
metadata:
  name: mongo
  namespace: microservices
  labels:
    app: mongo
    app.kubernetes.io/component: mongo
    app.kubernetes.io/instance: mongo
    app.kubernetes.io/name: mongo
    app.kubernetes.io/part-of: microservices
    app.openshift.io/runtime: mongodb
    app.openshift.io/runtime-namespace: microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
        deployment: mongo
    spec:
      volumes:
        - name: mongo-path
          persistentVolumeClaim:
            claimName: pvc-database
      containers:
        - name: mongo
          image: image-registry.openshift-image-registry.svc:5000/microservices/is-mongo:latest
          terminationMessagePath: /dev/termination-log
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: root
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: example
          ports:
            - containerPort: 27017
              protocol: TCP
          imagePullPolicy: Always
          volumeMounts:
            - name: mongo-path
              mountPath: /data/configdb
            - name: mongo-path
              mountPath: /data/db
          terminationMessagePolicy: File
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
