kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: is-mongo
  namespace: microservices
  labels:
    app: mongo
    app.kubernetes.io/component: mongo
    app.kubernetes.io/instance: mongo
    app.kubernetes.io/name: mongo
    app.kubernetes.io/part-of: microservices
spec:
  tags:
    - name: latest
      from:
        kind: DockerImage
        name: mongo
      importPolicy:
        importMode: Legacy
      referencePolicy:
        type: Local
