apiVersion: v1
kind: Service
metadata:
  name: svc-frontend
  namespace: microservices
  labels:
    app: microservices
    app.kubernetes.io/part-of: microservices
spec:
  selector:
    app: microservices
  ports:
    - name: frontend-tcp
      protocol: TCP
      port: 3300
      targetPort: frontend-port
