kind: Service
apiVersion: v1
metadata:
  name: mongo
  namespace: microservices
  labels:
    app: mongo
    app.kubernetes.io/component: mongo
    app.kubernetes.io/instance: mongo
    app.kubernetes.io/name: mongo
    app.kubernetes.io/part-of: microservices
spec:
  selector:
    app: mongo
    deployment: mongo
  ports:
    - name: 27017-tcp
      protocol: TCP
      port: 27017
      targetPort: 27017

