apiVersion: v1
kind: Service
metadata:
  name: svc-microservices
  namespace: microservices
  labels:
    app: microservices
    app.kubernetes.io/part-of: microservices
spec:
  selector:
    app: microservices
  ports:
    - name: gateway-tcp
      protocol: TCP
      port: 3400
      targetPort: gateway-port
    - name: security-tcp
      protocol: TCP
      port: 3500
      targetPort: security-port
    - name: vehicle-tcp
      protocol: TCP
      port: 3600
      targetPort: vehicle-port
