kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: is-frontend-docker
  namespace: microservices
  labels:
    app: microservices
    app.kubernetes.io/part-of: microservices
spec:
  tags:
  - name: "latest"
    from:
      kind: DockerImage
      name: dey125r/dey-frontend-microservices-openshift:latest
    referencePolicy:
      type: Source